function genCoupFiles(prefix,steam_table)
% genCoupFiles - builds .files file for the coupled run
%
%

fid = fopen(sprintf('%s.files',prefix),'w+');


strings={...
    [sprintf('root: %s',prefix)],...
    [sprintf('input: %s.dat',prefix)],...
    [sprintf('outpu: %s.out',prefix)],...
    [sprintf('grida: %s.fehm',prefix)],...
    [sprintf('storo: %s.stor',prefix)],...
    [sprintf('rsti: %s.ini',prefix)],...
    [sprintf('rsto: %s.fin',prefix)],...
    [sprintf('error: %s.err',prefix)],...
    [sprintf('check: %s.chk',prefix)],...
    [sprintf('zone: %s.zone',prefix)],...
    [sprintf('hist: %s.hist',prefix)],...
    [sprintf('h2oin: %s',steam_table)],...
    [''],...
    ['all']};

%Write output
disp(['Writing output to: ',sprintf('%s.files',prefix)])

fprintf(fid,'%s\n',strings{1:end-1});
fprintf(fid,'%s',strings{end});


fclose(fid);

end
