function bob1 = import_avs_log(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BOB1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  BOB1 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  bob1 = importfile("/home/rperrin/Geofluids/Matlab_testing/lagrit_testing/bobs_test/bob.avs_log", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Feb-2022 11:46:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["FilePrefix", "days", "V330linUbuntu"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
% opts = setvaropts(opts, ["VarName1", "FEHM"], "TrimNonNumeric", true);
% opts = setvaropts(opts, ["VarName1", "FEHM"], "ThousandsSeparator", ",");

% Import the data
bob1 = readtable(filename, opts);

end