function [outputArg1,outputArg2] = writeDatFile(prefix,conduction_flag,sim_length)
%UNTITLED9 Summary of this function goes here
%   Detailed explanation goes here
fid = fopen(sprintf('%s.dat',prefix),'w+');

strings={...
['# bob_cond.dat'],...
['# ----------------------------SOLUTION TYPE---------------------------'],...
['sol'],...
['-1  -1'],...
['# -----------------------CONTOUR OUTPUT REQUESTS----------------------'],...
['cont'],...
['surf   100000  365e7'],...
['xyz'],...
['temperature'],...
['material'],...
['flux'],...
['pressure'],...
['liquid'],...
['saturation'],...
['permeability'],...
['velocity'],...
['source'],...
['endavs'],...
['end'],...
['# ----------------------INITIAL VARIABLE GRADIENTS--------------------'],...
['init'],...
  [' 20.5   0.0  2.  0.  0.  2.  0., 0.'],...
['# -----------------------------PERMEABILITY---------------------------'],...
['zone'],...
['file'],...
['mesh_tet_material.zone'],...
['perm'],...
['file'],...
['bob.perm'],...
['# -----------------------------ROCK CONDUCTIVITY----------------------'],...
['cond'],...
['file'],...
['bob.cond'],...
['ppor'],...
['file'],...
['bob.ppor'],...
['# ---------------------EQUATIONS OF STATE-----------------------------'],...
['#eos'],...
['#file'],...
['#bob.wpi'],...
['# ----------------------PRODUCTION------------------------------------'],...
['zone'],...
['file'],...
['bob_outside.zone'],...
['hflx'],...
['-00001 0 0 2.0 1.e6'],...
['0'],...
['hflx'],...
['file'],...
['bob.hflx'],...
['flow'],...
['file'],...
['bob.flow'],...
['# ----------------------MAT PROPERTIES--------------------------------'],...
['rock'],...
['file'],...
['bob.rock'],...
['# -----------------------TIME STEPPING PARAMETERS---------------------'],...
['time'],...
 ['1.e-4 1.825e9  10000  10  0   1   0'],...
[''],...
['# --------------------SIM CONTROL PARAMETERS--------------------------'],...
['ctrl'],...
['-50  1.00e-04  25  100 gmre'],...
['1  0  0  2'],...
[''],...
['1  3  1.0'],...
['7  1.3  1.0e-06  3650000.0'],...
['0  1'],...
['stop']};



end